### ISSUE TITLE
Set up react-router

### ISSUE THREAD

**Issue by meiamsome** [CodingTrain/project-trainsite-frontend#9]
Set up react-router to work at a basic level. As there's no pages yet, this is essentially installing it and setting up the <Router> component w/ browser history

**Comment by Fraasi** [comment]
I'm otherwise done with this, but when trying to add the brower history I get the evil typescript error
```sh
Failed to compile
G:/Code/GitClones/project-trainsite-frontend/src/App.tsx
Type error: Type '{ children: Element; history: History<any>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<BrowserRouter> & Readonly<{ children?: ReactNode; }> & Readonly<BrowserRouterProps>'.
  Property 'history' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<BrowserRouter> & Readonly<{ children?: ReactNode; }> & Readonly<BrowserRouterProps>'.  TS2322

    14 |       <CodingTrainThemeProvider>
    15 |         <Header />
  > 16 |         <Router history={history}>
       |          ^
    17 |           <main>
    18 |             <Route exact path="/" render={() => (
    19 |               <img src={pic} style={{ height: '120px' }} />
```

Any advice on how to fix this?  
Edit:  
I did install "@types/react-router-dom"
E2:  
Tried installing "@types/history", still doesn't work.
router branch [here](https://github.com/Fraasi/project-trainsite-frontend/tree/router/src) if you need to see what I've done.

**Comment by meiamsome** [comment]
@Fraasi As you are using the `BrowserRouter` you don't need to pass `history` as an argument I believe.

**Comment by Fraasi** [comment]
I tried to do it like [this](https://github.com/ReactTraining/react-router/blob/master/FAQ.md#how-do-i-access-the-history-object-outside-of-components), but did not get it working,
I removed history and types, and now I got my little example working, but I can't get my test to pass  
```
 FAIL  src/components/Button/index.test.tsx (9.695s)
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: The prop `history` is marked as required in `Router`, but its value is `undefined`.
          in Router (at Button/index.test.tsx:11)
    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [TypeError: Cannot read property 'location' of undefined]
          at reportException (G:\Code\GitClones\project-trainsite-frontend\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
```
I will make a pull request as it is now, maybe we can fix this later since I seem to be way out of my comfort zone on this one and I think react-router documentation is either out-of-date or just confusing.
